Repository Electric-Coin-Company/zcash-android-wallet-sdk, pull requests merged in 2023-06, with the labels that each got.

#1065 [#920] Rust backend void return
  backend-lib/src/main/java/cash/z/ecc/android/sdk/internal/Backend.kt
  backend-lib/src/main/java/cash/z/ecc/android/sdk/internal/jni/RustBackend.kt
  sdk-lib/src/androidTest/java/cash/z/ecc/fixture/FakeRustBackend.kt
  sdk-lib/src/main/java/cash/z/ecc/android/sdk/block/CompactBlockProcessor.kt
  sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/BackendExt.kt
  sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/TypesafeBackend.kt
  sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/TypesafeBackendImpl.kt
  sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/db/derived/DerivedDataDb.kt
  sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/model/BlockBatch.kt
  sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/storage/block/FileCompactBlockRepository.kt
Labels: enhancement

#922 [#921] AGP 8.0.2
  .github/ISSUE_TEMPLATE/dependency.md
  .github/workflows/pull-request.yml
  backend-lib/build.gradle.kts
  build-conventions/buildscript-gradle.lockfile
  build-conventions/gradle.lockfile
  build-conventions/src/main/kotlin/zcash-sdk.android-conventions.gradle.kts
  build-conventions/src/main/kotlin/zcash-sdk.rosetta-conventions.gradle.kts
  build.gradle.kts
  demo-app-benchmark-test/build.gradle.kts
  demo-app-benchmark-test/proguard-consumer.txt
  demo-app/build.gradle.kts
  demo-app/proguard-project.txt
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  lightwallet-client-lib/build.gradle.kts
  lightwallet-client-lib/proguard-consumer.txt
  sdk-lib/build.gradle.kts
Labels: tech_debt, dependencies

#1085 [#1066] Detekt enhancement
  backend-lib/src/androidTest/java/cash/z/ecc/android/sdk/internal/jni/RustDerivationToolTest.kt
  darkside-test-lib/src/androidTest/java/cash/z/ecc/android/sdk/darkside/MultiAccountIntegrationTest.kt
  darkside-test-lib/src/androidTest/java/cash/z/ecc/android/sdk/darkside/MultiAccountTest.kt
  darkside-test-lib/src/androidTest/java/cash/z/ecc/android/sdk/darkside/MultiRecipientIntegrationTest.kt
  darkside-test-lib/src/androidTest/java/cash/z/ecc/android/sdk/darkside/OutboundTransactionsTest.kt
  darkside-test-lib/src/androidTest/java/cash/z/ecc/android/sdk/darkside/reorgs/InboundTxTests.kt
  darkside-test-lib/src/androidTest/java/cash/z/ecc/android/sdk/darkside/reorgs/ReorgBasicTest.kt
  darkside-test-lib/src/androidTest/java/cash/z/ecc/android/sdk/darkside/reorgs/ReorgLargeTest.kt
  darkside-test-lib/src/androidTest/java/cash/z/ecc/android/sdk/darkside/reorgs/SetupTest.kt
  darkside-test-lib/src/androidTest/java/cash/z/ecc/android/sdk/darkside/test/DarksideTestCoordinator.kt
  darkside-test-lib/src/androidTest/java/cash/z/ecc/android/sdk/darkside/test/TestWallet.kt
  demo-app/src/androidTest/java/cash/z/wallet/sdk/sample/demoapp/SampleCodeTest.kt
  demo-app/src/androidTest/java/cash/z/wallet/sdk/sample/demoapp/preference/model/entry/BooleanPreferenceDefaultTest.kt
  demo-app/src/androidTest/java/cash/z/wallet/sdk/sample/demoapp/preference/model/entry/IntegerPreferenceDefaultTest.kt
  demo-app/src/androidTest/java/cash/z/wallet/sdk/sample/demoapp/preference/model/entry/StringPreferenceDefaultTest.kt
  demo-app/src/androidTest/java/cash/z/wallet/sdk/sample/demoapp/ui/common/Global.kt
  demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/preference/model/entry/BooleanPreferenceDefault.kt
  demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/preference/model/entry/IntegerPreferenceDefault.kt
  demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/ui/screen/home/view/HomeView.kt
  demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/ui/screen/home/viewmodel/WalletViewModel.kt
  demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/ui/screen/seed/view/ConfigureSeedView.kt
  gradle.properties
  sdk-incubator-lib/src/androidTest/kotlin/cash/z/ecc/android/sdk/Global.kt
  sdk-incubator-lib/src/androidTest/kotlin/cash/z/ecc/android/sdk/model/FiatCurrencyConversionRateStateTest.kt
  sdk-incubator-lib/src/androidTest/kotlin/cash/z/ecc/android/sdk/model/PersistableWalletTest.kt
  sdk-incubator-lib/src/androidTest/kotlin/cash/z/ecc/android/sdk/model/ZecStringExtTest.kt
  sdk-incubator-lib/src/main/java/cash/z/ecc/android/sdk/model/CurrencyConversion.kt
  sdk-lib/src/androidTest/java/cash/z/ecc/android/sdk/annotation/MaintainedTest.kt
  sdk-lib/src/androidTest/java/cash/z/ecc/android/sdk/ext/TestExtensions.kt
  sdk-lib/src/androidTest/java/cash/z/ecc/android/sdk/fixture/WalletFixture.kt
  sdk-lib/src/androidTest/java/cash/z/ecc/android/sdk/integration/TestnetIntegrationTest.kt
  sdk-lib/src/androidTest/java/cash/z/ecc/android/sdk/internal/storage/block/FileCompactBlockRepositoryTest.kt
  sdk-lib/src/androidTest/java/cash/z/ecc/android/sdk/jni/BranchIdTest.kt
  sdk-lib/src/androidTest/java/cash/z/ecc/android/sdk/jni/TransparentTest.kt
  sdk-lib/src/androidTest/java/cash/z/ecc/android/sdk/sample/ShieldFundsSample.kt
  sdk-lib/src/androidTest/java/cash/z/ecc/android/sdk/sample/TransparentRestoreSample.kt
  sdk-lib/src/androidTest/java/cash/z/ecc/android/sdk/util/TestWallet.kt
  sdk-lib/src/main/java/cash/z/ecc/android/sdk/Synchronizer.kt
  sdk-lib/src/main/java/cash/z/ecc/android/sdk/block/CompactBlockProcessor.kt
  sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/block/CompactBlockDownloader.kt
  tools/detekt-baseline.xml
  tools/detekt.yml
Labels: enhancement

#1087 [#1048] Duration instead of Long
  sdk-lib/src/main/java/cash/z/ecc/android/sdk/block/CompactBlockProcessor.kt
Labels: enhancement

#1091 [#1088] Demo: Add Missing Compose Previews
  demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/ui/screen/addresses/view/AddressesView.kt
  demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/ui/screen/balance/view/BalanceView.kt
  demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/ui/screen/send/view/SendView.kt
  demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/ui/screen/transactions/view/Transactions.kt
Labels: enhancement, demo-app
